modLoader = "javafml"
loaderVersion = "[33,)"
license = "BSD-3-Clause License for Code"
# issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]]
modId = "silveroakoutpost"
version = "${file.jarVersion}"
displayName = "Silveroak Outpost"
# updateJSONURL="http://myurl.me/"
# displayURL="http://example.com/"
logoFile = "logo.png"
credits = "Thanks for this example mod goes to Java"
authors = "Love, Cheese and small house plants"
description = ''' '''
[[dependencies.silveroakoutpost]]
modId = "forge"
mandatory = true
versionRange = "[33,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.silveroakoutpost]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2]"
ordering = "NONE"
side = "BOTH"
